from datetime import datetime, timedelta

clientAndAccountReps = {
    "bom_name": "Quotation",
    "contact_name": "Maxime Laviolette",
    "comp_name": "Telesat",
    "comp_address": "160 Elgin Street - Suite 2100",
    "comp_city": "Ottawa",
    "comp_state": "ON",
    "comp_zip": "K2P 2P7",
    "comp_phone": "+1 (888) 932-6666",
    "term": "10/10/2025 to 10/09/2026",
    "payment_terms": "Net 30, O.A.C.",
    "incoterms": "DAP",
    "currency": "USD",
    "duty": "Included",
    "taxes": "Excluded",
    "sales_desk_email": "orders@spitfirenetworks.com",
    "owner_name": "Paul Kushnirenko",
    "owner_email": "paul.kushnirenko@spitfirenetworks.com",
    "owner_phone": "+1 (416) 809-9372",
    # "quote_number": f"Q-{datetime.now().strftime('%y%m%d%M%S')}",
    "date": datetime.now().strftime("%m/%d/%Y"),
    "expiry": (datetime.now() + timedelta(days=30)).strftime("%m/%d/%Y"),
    "round_values": "False",
    "add_notes": [],
}