from datetime import datetime, timedelta

clientAndAccountReps = {
    "bom_name": "Quotation",
    "contact_name": "Jerry Leveillee",
    "comp_name": "Publix Super Markets",
    "comp_address": "3300 Publix Corporate Pkwy",
    "comp_city": "Lakeland",
    "comp_state": "FL",
    "comp_zip": "33811",
    "comp_phone": "+1 (863) 688-1188",
    "term": "Per Line Item",
    "payment_terms": "Net 30, O.A.C.",
    "incoterms": "DAP",
    "currency": "USD",
    "duty": "Included",
    "taxes": "Excluded",
    "sales_desk_email": "orders@spitfirenetworks.com",
    "owner_name": "Brandon Hepburn",
    "owner_email": "brandon@spitfirenetworks.com",
    "owner_phone": "+1 (613) 668-0299",
    # "quote_number": f"Q-{datetime.now().strftime('%y%m%d%M%S')}",
    "date": datetime.now().strftime("%m/%d/%Y"),
    "expiry": "December 31st, 2025",
    "round_values": "False",
    "add_notes": [],
}
